services:
    db:
        image: ${DB_IMAGE}
        restart: always
        ports:
          - ${DB_PORT}:${DB_PORT}
        environment: 
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_DATABASE}